from libs.stats import StatsEnum

upgrades = [StatsEnum.StatSpeed,
            StatsEnum.StatSpeed,
            StatsEnum.StatRange,
            StatsEnum.StatHealthRegeneration,
            StatsEnum.StatHealthRegeneration,
            StatsEnum.StatHealthRegeneration,
            StatsEnum.StatHealthRegeneration,
            StatsEnum.StatSpeed,
            StatsEnum.StatRange,
            StatsEnum.StatHealthMax,
            StatsEnum.StatHealthMax,
            StatsEnum.StatHealthMax,
            StatsEnum.StatHealthMax,
            StatsEnum.StatRange,
            StatsEnum.StatRange,
            StatsEnum.StatSpeed,
            StatsEnum.StatHealthMax,
            StatsEnum.StatHealthMax,
            StatsEnum.StatHealthRegeneration,
            StatsEnum.StatBodyDamage,
            StatsEnum.StatBodyDamage,
            StatsEnum.StatBodyDamage,
            StatsEnum.StatBodyDamage,
            StatsEnum.StatBodyDamage,
            StatsEnum.StatHealthRegeneration,
            StatsEnum.StatHealthRegeneration,
            StatsEnum.StatHealthMax,
            StatsEnum.StatSpeed,
            StatsEnum.StatBodyDamage,
            StatsEnum.StatBodyDamage
            ]
